### ISSUE TITLE
Switch to Hybrid fails

### ISSUE THREAD

**Issue by jediafr** [Shatur/optimus-manager-qt#33]
It may not be a bug per se but The Hybrid mode once selected is defaulting to intel on my laptop.
Intel mode / Nvidia mode are working fine.

**To Reproduce**

1.  Go to '...'Systray
2.  Click on '....'Hybrid

**Expected behavior**
I expected the hybrid icon to appear on the systray after logout/login.

**Environment (please complete the following information):**

-   OS: (Manjaro)
-   Desktop environment: (KDE)
-   Optimus Manager version: (e.g. 1.0.0)
-   Optimus Manager Qt version: (optimus-manager-qt  1.4.3-1)

In fact i dont know what hybrid would do , is it Prime offloading or just blumblebee ?

**Comment by Shatur** [comment]
> Optimus Manager version: (e.g. 1.0.0)

You must to specify Optimus Manager version.

Is it switching with Optimus Manager?

**Comment by jediafr** [comment]
of course sorry about that : 
Optimus Manager : 1.2.2-2.1
Blumblebee 3.2.1-22
Kernel 4.14 bbswitch 0.8-127

I ddnt try with the optimus manager cli though (what would be the command ?)

**Comment by Shatur** [comment]
Please read the [Optimus Manager](https://github.com/Askannz/optimus-manager/) documentation first before using. Optimus Manager is incompatible with Bumblebee since both tools would be trying to control GPU power switching at the same time. For hybrid mode you also need patched kernel. This repo is only for GUI-related issues.
